// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB05KjoYOuX9ydnt-F-DhdS8odp_QbQHfk',
    appId: '1:1011012681251:web:2ddab3883e49090225bb96',
    messagingSenderId: '1011012681251',
    projectId: 'zoom-clone-webrtc',
    authDomain: 'zoom-clone-webrtc.firebaseapp.com',
    storageBucket: 'zoom-clone-webrtc.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBAz5TLd66ya-R7JNS-AoLBYq1g6ImL7PE',
    appId: '1:1011012681251:android:cd3a50a28545efb025bb96',
    messagingSenderId: '1011012681251',
    projectId: 'zoom-clone-webrtc',
    storageBucket: 'zoom-clone-webrtc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCawrcN20HvkA5eRDikPvADc3Ua_Cd5S9Q',
    appId: '1:1011012681251:ios:201ffb97ee0ec8bd25bb96',
    messagingSenderId: '1011012681251',
    projectId: 'zoom-clone-webrtc',
    storageBucket: 'zoom-clone-webrtc.appspot.com',
    iosClientId: '1011012681251-rv1j4bi9h1boj2crm9hj380t54bo0ag3.apps.googleusercontent.com',
    iosBundleId: 'com.example.zoomClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCawrcN20HvkA5eRDikPvADc3Ua_Cd5S9Q',
    appId: '1:1011012681251:ios:201ffb97ee0ec8bd25bb96',
    messagingSenderId: '1011012681251',
    projectId: 'zoom-clone-webrtc',
    storageBucket: 'zoom-clone-webrtc.appspot.com',
    iosClientId: '1011012681251-rv1j4bi9h1boj2crm9hj380t54bo0ag3.apps.googleusercontent.com',
    iosBundleId: 'com.example.zoomClone',
  );
}
